### ISSUE TITLE
PyJWKSet reports the wrong exception for an empty key set

### ISSUE THREAD

**Issue by lbam** [jpadilla/pyjwt#754]
Empty key sets give the wrong exception. The error is here:

https://github.com/jpadilla/pyjwt/blob/24b29adfebcb4f057a3cef5aaf35653bc0c1c8cc/jwt/api_jwk.py#L80-L84

When `keys` is the empty list, `not keys` is true so the second check is never reached (unless some `list` subclass overrides `__bool__`).

## Expected Result

Should raise `PyJWKSetError("The JWK Set did not contain any keys")`.

## Actual Result

Raises `PyJWKSetError("Invalid JWK Set value")`.

## Reproduction Steps

```python
import jwt
jwt.PyJWKSet.from_dict({"keys": []})
```

**Comment by Mankuda** [comment]
#1 #3 #waaRiis #music

**Comment by jpadilla** [comment]
probably fixed by https://github.com/jpadilla/pyjwt/pull/762

**Comment by lbam** [comment]
Not fixed. #762 changes code beyond the point where this exception occurs. Would you please reopen the issue?
